=== Financial-Information-Technology-Ltd/cdn/html/command.dtd
<!ELEMENT RelatedCommands (CommandRelation*)>

<!ELEMENT CommandRelation (MainCommand, Command*)>

<!ELEMENT MainCommand (#PCDATA)>

<!ELEMENT Command (#PCDATA)>

=== Financial-Information-Technology-Ltd/cdn/html/commands.xml
<?xml version="1.0"?>
<!DOCTYPE RelatedCommands SYSTEM "command.dtd">
<RelatedCommands>
    <CommandRelation>
        <MainCommand>DO_MAIN_PAGE</MainCommand>
        <Command>SHOW_WORKFLOW</Command>
        <Command>WORKFLOW_TASK</Command>
        <Command>DO_SEARCH_PSEUDO</Command>
        <Command>DO_SEARCH_SORTCODE</Command>
        <Command>DO_SEARCH_MERGE</Command>
        <Command>EDIT_COUNTRY_LIST</Command>
        <Command>LIST_CITIES</Command>
        <Command>DO_ADDRESS_LOOKUP</Command>
        <Command>FIT_JS</Command>
        <Command>WEBSOCKET</Command>
    </CommandRelation>
    <CommandRelation>
        <MainCommand>DO_POLICY_ENQUIRY</MainCommand>
        <Command>CHOOSE_POLICY</Command>
        <Command>DO_SHOW_POLICY</Command>
        <Command>SHOW_POLICY</Command>
        <Command>DO_SHOW_POLICY_FUND</Command>
        <Command>POLICY_ENQUIRY</Command>
        <Command>DO_POLICY_LIST</Command>
        <Command>POLICY_LIST</Command>
        <Command>SHOW_POLICY_COMMISSIONS</Command>
        <Command>DO_SHOW_OVERRIDE_DETAILS</Command>
        <Command>SHOW_POLICY_VALUE</Command>
        <Command>SHOW_STATUS_HISTORY</Command>
        <Command>SHOW_POLICY_ACTIVITY</Command>
        <Command>COUPON_LIST</Command>
        <Command>SHOW_COUPON</Command>
        <Command>SHOW_CASH_MOVEMENTS</Command>
        <Command>SHOW_DEPOSIT_ACTIVITY</Command>
        <Command>SHOW_ANNUITY_ACTIVITY</Command>
        <Command>SHOW_LOAN_ACTIVITY</Command>
        <Command>SHOW_IPAYMENT_ACTIVITY</Command>
        <Command>SHOW_POLACCTRN_ENTRY</Command>
        <Command>SHOW_POLICY_UNIT_MOVEMENT</Command>
        <Command>SHOW_UNITMOVE_ENTRY</Command>
        <Command>SHOW_POLICY_UNITACCTRN</Command>
        <Command>SHOW_UNITACCTRN_ENTRY</Command>
        <Command>SHOW_POLICY_COMM_LIST</Command>
        <Command>SHOW_POLICY_AGENT_SALARY_JOURNALS</Command>
        <Command>SHOW_POLICY_FUTURE</Command>
        <Command>SHOW_POLICY_IPAYMENTS</Command>
        <Command>SHOW_POLICY_SEGMENTS</Command>
        <Command>SHOW_PAYMENT_RECEIPT_HISTORY</Command>
        <Command>SHOW_POLICY_VALUE_GRAPH</Command>
        <Command>SHOW_POLICY_VALUE_GRAPH_CHOOSE</Command>
        <Command>SHOW_POLICY_VALUE_GRAPH_IMG</Command>
        <Command>DO_SHOW_UWRREQ</Command>
        <Command>SHOW_POLICY_UWRREQ</Command>
        <Command>SHOW_FUND_SPLIT</Command>
        <Command>SHOW_TBMVR_RATES</Command>
        <Command>POLICY_UNIT_STATEMENT</Command>
        <Command>POLICY_UNIT_STATEMENT_PROCESS</Command>
        <Command>POLICY_MEMBER_STATEMENT</Command>
        <Command>POLICY_MEMBER_STATEMENT_PROCESS</Command>
        <Command>UNRESOLVED_UNDERWRITING</Command>
        <Command>SHOW_POLICY_DD_REVERSALS</Command>
        <Command>SHOW_POLICY_COMPANY_UNIT_MOVEMENTS</Command>
        <Command>SHOW_COMPANY_UNITMOVE_ENTRY</Command>
        <Command>DO_SEARCH_CLIENT</Command>
        <Command>SEARCH_CLIENT</Command>
        <Command>DO_SEARCH_MEMBER_IMPORT</Command>
        <Command>SEARCH_MEMBER_IMPORT</Command>
        <Command>POLICY_ENDORSEMENTS_LIST</Command>
        <Command>SHOW_POLICY_ENDORSEMENT</Command>
        <Command>EXTERNAL_BANK_ACCOUNT</Command>
        <Command>SHOW_POLICY_NOTES</Command>
        <Command>POLICY_NOTES</Command>
        <Command>SHOW_GROUP_NOTES</Command>
        <Command>GROUP_NOTES</Command>
        <Command>EDIT_NOTE</Command>
        <Command>SHOW_CLIENT</Command>
        <Command>SHOW_CLIENT_NOTES</Command>
        <Command>CLIENT_NOTES</Command>
        <Command>SHOW_AGENT_NOTES</Command>
        <Command>AGENT_NOTES</Command>
        <Command>DISTRIBUTION_FUNDS</Command>
        <Command>POLICY_MIRROR_UNITS</Command>
        <Command>SHOW_POLICY_PAYMENTS_OUT_LIST</Command>
        <Command>SHOW_PAYMENTS_OUT</Command>
        <Command>SHOW_WORKFLOW_POLICY</Command>
        <Command>SHOW_POLICY_DATA</Command>
        <Command>SHOW_POLICY_ANNUITY</Command>
        <Command>SHOW_ANNUITY</Command>
        <Command>DO_SEARCH_AGENT</Command>
        <Command>SEARCH_AGENT</Command>
        <Command>DOWNLOAD_CLIENT_MONEY_IN_OUT</Command>
        <Command>SHOW_POLICY_LOANS</Command>
        <Command>SURRENDER_QUOTE</Command>
        <Command>DO_SEARCH_POLICY</Command>
        <Command>SEARCH_POLICY</Command>
        <Command>SHOW_FUND_SPLIT_PIE</Command>
        <Command>LIST_POLICY_ANSWERS</Command>
        <Command>SHOW_POLICY_ANSWERS</Command>
        <Command>SHOW_SWITCH_REQUEST</Command>
        <Command>SHOW_POLICY_MORTALITY_LOADING</Command>
        <Command>SHOW_CLIENT_COMPLIANCE</Command>
    </CommandRelation>
    <CommandRelation>
        <MainCommand>DO_MAINTAIN_POLICY</MainCommand>
        <Command>MAINTAIN_POLICY</Command>
        <Command>IPAYMENT_DATA</Command>
        <Command>POLICY_IPAYMENTS</Command>
        <Command>DO_SHOW_REGULAR_INCOME</Command>
        <Command>DO_STATUS_CHANGE</Command>
        <Command>STATUS_CHANGE</Command>
        <Command>DO_COVERAGE_STATUS_CHANGE</Command>
        <Command>COVERAGE_STATUS_CHANGE</Command>
        <Command>COVERAGE_STATUS_CHANGE_REVIEW</Command>
        <Command>STATUS_CHANGE_DEATH</Command>
        <Command>STATUS_CHANGE_CI</Command>
        <Command>STATUS_CHANGE_REVIEW</Command>
        <Command>STATUS_CHANGE_PREM_HOLIDAY</Command>
        <Command>STATUS_CHANGE_MATURITY_SETTLEMENT</Command>
        <Command>STATUS_CHANGE_WP</Command>
        <Command>STATUS_CHANGE_WC</Command>
        <Command>POLICY_UWRREQ</Command>
        <Command>UWRREQ_PROVIDER</Command>
        <Command>UWRREQ_PROVIDER_FEES</Command>
        <Command>MORTALITY_RATING</Command>
        <Command>SHOW_VERIFY_MORTALITY_RATING</Command>
        <Command>PROCESS_VERIFY_MORTALITY_RATING</Command>
        <Command>CHANGE_TRAIL_COMM</Command>
        <Command>SHOW_POLICY_WITHDRAWAL</Command>
        <Command>POLICY_WITHDRAWAL</Command>
        <Command>PROCESS_UNIT_WITHDRAWAL</Command>
        <Command>PROCESS_UNIT_WITHDRAWAL_TERMINATION</Command>
        <Command>PROCESS_UNIT_WITHDRAWAL_TERMINATION2</Command>
        <Command>DO_UNIT_SWITCH</Command>
        <Command>SET_UNIT_SWITCH</Command>
        <Command>PROCESS_UNIT_SWITCH</Command>
        <Command>DO_CHOOSE_UNITDATE</Command>
        <Command>CHANGE_FUND_SPLIT</Command>
        <Command>CHANGE_TBMVR_RATES</Command>
        <Command>POLICY_REINSURANCE</Command>
        <Command>PREMIUM_ENDORSEMENT</Command>
        <Command>POLICY_BENEFICIARIES</Command>
        <Command>ADD_SEGMENT</Command>
        <Command>EDIT_SEGMENT_LIST</Command>
        <Command>ADD_SEGMENT_RESULTS</Command>
        <Command>DO_ADD_RIDER</Command>
        <Command>ADD_RIDER</Command>
        <Command>CHOOSE_NEW_RIDER</Command>
        <Command>DO_ENDORSE_POLICY</Command>
        <Command>ENDORSE_POLICY</Command>
        <Command>DO_ENDORSE_SUM_ASSURED</Command>
        <Command>ENDORSE_SUM_ASSURED</Command>
        <Command>SHOW_SURRENDERS</Command>
        <Command>SHOW_SURRENDERS_NOSUBMIT</Command>
        <Command>PROCESS_SURRENDERS</Command>
        <Command>MODEMETHOD_CHANGE</Command>
        <Command>MODEMETHOD_CHANGE_BANK</Command>
        <Command>DO_SEARCH_CLIENT</Command>
        <Command>EXTERNAL_BANK_ACCOUNT</Command>
        <Command>EDIT_PAYMENT_OUT</Command>
        <Command>REPAY_SUSPENSE</Command>
        <Command>POLICY_SF_ANNUITY</Command>
        <Command>PLAN_SUBSTITUTION</Command>
        <Command>CREATE_UWRREQ</Command>
        <Command>SHOW_UWRREQ</Command>
        <Command>EDIT_POLICY_ANNUITY</Command>
        <Command>PROCESS_REVERSIONARY_ANNUITY</Command>
        <Command>DO_EDIT_ANNUITY</Command>
        <Command>EDIT_ANNUITY</Command>
        <Command>SHOW_POLICY_CHARGES</Command>
        <Command>PROCESS_POLICY_CHARGES</Command>
        <Command>DO_JOIN_GROUP</Command>
        <Command>JOIN_GROUP</Command>
        <Command>DO_LEAVE_GROUP</Command>
        <Command>LEAVE_GROUP</Command>
        <Command>POLICY_PENDING_ENDORSEMENTS</Command>
        <Command>EDIT_POLICY_ENDORSEMENT</Command>
        <Command>PROCESS_ENDORSEMENT</Command>
        <Command>POLICY_DD_STATUS_CHANGE</Command>
        <Command>SHOW_PENDING_STATUS_CHANGE</Command>
        <Command>EDIT_PENDING_STATUS_CHANGE</Command>
        <Command>CANCEL_PENDING_STATUS_CHANGE</Command>
        <Command>EDIT_SWITCH_REQUEST</Command>
        <Command>PROCESS_SWITCH_REQUEST</Command>
        <Command>POLICY_LAPSE_DATE_CHANGE</Command>
        <Command>POLICY_DD_DATE_CHANGE</Command>
        <Command>PAYER_ACCOUNT_CHANGE</Command>
        <Command>REVERSE_PREMIUM</Command>
        <Command>EDIT_POLICY_LOANS</Command>
        <Command>POLICY_LOANS</Command>
        <Command>LOAN_EDIT</Command>
        <Command>POLICY_TERM_CHANGE</Command>
        <Command>POLICY_SPECIAL_CLAUSE</Command>
        <Command>SHOW_POLICY_SPECIAL_CLAUSE</Command>
        <Command>PROCESS_ANNUITY_PAYMENT</Command>
        <Command>PROCESS_ADJUST_ANNUITY</Command>
        <Command>EDIT_POLICY_UWRREQ</Command>
        <Command>POLICY_REINS_CHANGE</Command>
        <Command>POLICY_REINS_CHANGE_LWY</Command>
        <Command>PROCESS_PAY_PREMIUM_FROM_SUSPENSE</Command>
        <Command>CHANGE_COMM_RATE</Command>
        <Command>CHANGE_RENEWAL_COMM_RATE</Command>
        <Command>CHANGE_INVESTMENT_ADVISOR_COMM_RATE</Command>
        <Command>POLICY_REPLACEMENT</Command>
        <Command>MODIFY_POLICY</Command>
        <Command>WAIVER_RECERTIFICATION</Command>
        <Command>MODIFY_POLICY_FEE_STRUCTURE</Command>
        <Command>FRAUD_CHECK</Command>
        <Command>MODIFY_RENEWAL_COMMISSION</Command>
        <Command>AEI_CLASSIFICATION</Command>
        <Command>FUND_PORTFOLIO_CHANGE</Command>
        <Command>DO_BACKDATED_JOB_LOSS_CLAIM</Command>
        <Command>PROCESS_BACKDATED_JOB_LOSS_CLAIM</Command>
    </CommandRelation>
    <CommandRelation>
        <MainCommand>EDIT_FUND</MainCommand>
        <Command>FUND_CODE_CHOOSE</Command>
        <Command>FUND_CODE_DETAILS</Command>
