=== Financial-Information-Technology-Ltd/cdn/html/menu.dtd
<!ELEMENT UserSecurity (FitMenu,AllowedCommands,PolicyMaintenanceButtons,GroupSchemeMaintenanceButtons,ClientButtons,AllowedCommandsOther)>

<!ELEMENT FitMenu ( (Description | Submenu | Item | Text)*)>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT Submenu (Prompt,(Submenu | Item)*)>
<!ATTLIST Submenu id CDATA #REQUIRED>

<!ELEMENT Item (Prompt,Command)>

<!ELEMENT Prompt (#PCDATA)>

<!ELEMENT Command (#PCDATA)>
<!ATTLIST Command id CDATA #IMPLIED>

<!ELEMENT Text (#PCDATA)>

<!ELEMENT PolicyMaintenanceButtons (ButtonName*)>

<!ELEMENT GroupSchemeMaintenanceButtons (ButtonName*)>
<!ELEMENT ClientButtons (ButtonName*)>

<!ELEMENT ButtonName (#PCDATA)>

<!ELEMENT AllowedCommands (Command*)>

<!ELEMENT AllowedCommandsOther (Command*)>

=== Financial-Information-Technology-Ltd/cdn/html/PLL_OPERATIONS.XML
<?xml version="1.0"?>
<!DOCTYPE UserSecurity SYSTEM "menu.dtd">
<UserSecurity>
	<FitMenu>
		<Description>PLL Operations Menu</Description>
		<Submenu id="SUB_INDIVIDUAL">
			<Prompt>Individual</Prompt>
			<Item>
				<Prompt>New Business</Prompt>
				<Command>DO_NEW_BUSINESS</Command>
			</Item>
			<Item>
				<Prompt>Policy Workbench</Prompt>
				<Command>DO_POLICY_ENQUIRY</Command>
			</Item>
			<Item>
				<Prompt>Client Workbench</Prompt>
				<Command>DO_CLIENT_MAIN</Command>
			</Item>
			<Submenu id="SUB_AGENT">
				<Prompt>Agent SubMenu</Prompt>
				<Item>
					<Prompt>Agent Workbench</Prompt>
					<Command>DO_AGENT_MAIN</Command>
				</Item>
				<Item>
					<Prompt>Servicing Agents</Prompt>
					<Command>CHOOSE_SERV_AGENT_MAINTENANCE</Command>
				</Item>
				<Item>
					<Prompt>Statements</Prompt>
					<Command>DO_STATEMENTS</Command>
				</Item>
			</Submenu>
			<Item>
				<Prompt>Policy Diary Entry</Prompt>
				<Command>DO_SHOW_POLICY_DIARY_ENTRY</Command>
			</Item>
		</Submenu>
		<Submenu id="SUB_PAYMENT">
			<Prompt>Premium/Payment</Prompt>
			<Item>
				<Prompt>Policy Accounting</Prompt>
				<Command>MAKE_POLICY_ACCOUNTING</Command>
			</Item>
			<Item>
				<Prompt>Unreconciled transactions</Prompt>
				<Command>DO_UNRECONCILED_BANK_TRANS</Command>
			</Item>
		</Submenu>
		<Submenu id="SUB_WORKFLOW">
			<Prompt>Workflow</Prompt>
			<Item>
				<Prompt>New Task</Prompt>
				<Command>NEW_WORKFLOW_TASK</Command>
			</Item>
			<Item>
				<Prompt>List Tasks</Prompt>
				<Command>LIST_WORKFLOW_TASKS</Command>
			</Item>
			<Item>
				<Prompt>Schedule</Prompt>
				<Command>SHOW_WORKFLOW_SCHEDULE</Command>
			</Item>
		</Submenu>
		<Submenu id="SUB_SUPPORT_FILE">
			<Prompt>Support Files</Prompt>
			<Item>
				<Prompt>Custodian</Prompt>
				<Command>DO_CUSTODIAN_MAIN</Command>
			</Item>
			<Submenu id="SUB_SUPPORT_ORGANISATION">
				<Prompt>Organisation</Prompt>
				<Item>
					<Prompt>Company Documentation</Prompt>
					<Command>COMPANY_DOCUMENTATION_START</Command>
				</Item>
			</Submenu>
			<Item>
				<Prompt>Product Workbench</Prompt>
				<Command>CHOOSE_PLAN</Command>
			</Item>
			<Submenu id="SUB_REPORTS">
				<Prompt>Reports</Prompt>
				<Item>
					<Prompt>Create Reports</Prompt>
					<Command>EDIT_REPORT_WRITER</Command>
				</Item>
				<Item>
					<Prompt>Run Reports</Prompt>
					<Command>RUN_REPORTS</Command>
				</Item>
			</Submenu>
		</Submenu>
		<Submenu id="SUB_ADMINISTRATION">
			<Prompt>Administration</Prompt>
			<Item>
				<Prompt>Who is Logged On?</Prompt>
				<Command>LIST_SESSIONS</Command>
			</Item>
			<Item>
				<Prompt>Change Password</Prompt>
				<Command>DO_PASSWORD_CHANGE</Command>
			</Item>
			<Item>
				<Prompt>Out Of Office</Prompt>
				<Command>OUT_OF_OFFICE</Command>
			</Item>
		</Submenu>
		<Item>
			<Prompt>Logout</Prompt>
			<Command>DO_LOGIN</Command>
		</Item>
	</FitMenu>
	<AllowedCommands>
		<Command id="DO_MAINTAIN_POLICY">Maintain Policy</Command>
		<Command id="DO_MAINTAIN_CLIENT">Maintain Client</Command>
	</AllowedCommands>
	<PolicyMaintenanceButtons>
		<ButtonName>StatusChangeButton</ButtonName>
		<ButtonName>CoverageStatusChangeButton</ButtonName>
		<ButtonName>RiderClaimButton</ButtonName>
		<ButtonName>SwitchUnitsButton</ButtonName>
		<ButtonName>UwrreqButton</ButtonName>
		<ButtonName>RegularIncomeButton</ButtonName>
		<ButtonName>MortalityLoadingButton</ButtonName>
		<ButtonName>ChangeTrailerCommission</ButtonName>
		<ButtonName>UnitWithdrawalButton</ButtonName>
		<ButtonName>UnitReversalButton</ButtonName>
		<ButtonName>UnitWithdrawalTerminationButton</ButtonName>
		<ButtonName>SurrenderQuoteButton</ButtonName>
		<ButtonName>FundSplitButton</ButtonName>
		<ButtonName>UnitAdjustmentButton</ButtonName>
		<ButtonName>ReinsuranceButton</ButtonName>
		<ButtonName>PremiumEndorsementButton</ButtonName>
		<ButtonName>BeneficiariesButton</ButtonName>
		<ButtonName>AddSegmentButton</ButtonName>
		<ButtonName>AddRiderButton</ButtonName>
		<ButtonName>SegmentSurrenderButton</ButtonName>
		<ButtonName>ViewSegmentSurrenderButton</ButtonName>
		<ButtonName>ModemethodButton</ButtonName>
		<ButtonName>DistributionFunds</ButtonName>
		<ButtonName>CreatePaymentOutButton</ButtonName>
		<ButtonName>DoPolicyPaymentButton</ButtonName>
		<ButtonName>DoPolicyAccountingButton</ButtonName>
		<ButtonName>AnnuityButton</ButtonName>
		<ButtonName>PlanSubstitutionButton</ButtonName>
		<ButtonName>AdhocPolicyCharges</ButtonName>
		<ButtonName>PendingEndorsementsButton</ButtonName>
		<ButtonName>CancelPendingEndorsementButton</ButtonName>
		<ButtonName>CancelPendingStatusChangeButton</ButtonName>
		<ButtonName>CancelSwitchRequestButton</ButtonName>
		<ButtonName>ReversePremiumButton</ButtonName>
		<ButtonName>RepaySuspenseButton</ButtonName>
		<ButtonName>PayPremiumFromSuspenseButton</ButtonName>
		<ButtonName>ChangeCommRateButton</ButtonName>
	</PolicyMaintenanceButtons>
	<GroupSchemeMaintenanceButtons>
		<ButtonName>AllowMemberStrategyButton</ButtonName>
		<ButtonName>CalculateBillButton</ButtonName>
		<ButtonName>CalculateJoinersBillButton</ButtonName>
		<ButtonName>CancelBillButton</ButtonName>
		<ButtonName>ChangeCommRateButton</ButtonName>
		<ButtonName>ChangeInvestmentButton</ButtonName>
		<ButtonName>CreatePaymentOutButton</ButtonName>
		<ButtonName>CSVBillButton</ButtonName>
		<ButtonName>DoPolicyAccountingButton</ButtonName>
		<ButtonName>DoPolicyPaymentButton</ButtonName>
		<ButtonName>GroupSurrenderButton</ButtonName>
		<ButtonName>ImportMembersButton</ButtonName>
		<ButtonName>MedicalProviderButton</ButtonName>
		<ButtonName>MembershipButton</ButtonName>
		<ButtonName>PayJoinersPremiumButton</ButtonName>
		<ButtonName>PayPartialPremiumButton</ButtonName>
		<ButtonName>PayPremiumButton</ButtonName>
		<ButtonName>PrintJoinersBillButton</ButtonName>
		<ButtonName>RenewalDataButton</ButtonName>
		<ButtonName>ReversePremiumButton</ButtonName>
		<ButtonName>SignOffButton</ButtonName>
		<ButtonName>SignOffUndoButton</ButtonName>
		<ButtonName>StatementButton</ButtonName>
		<ButtonName>StatusChangeButton</ButtonName>
		<ButtonName>UwrreqButton</ButtonName>
		<ButtonName>WorkflowButton</ButtonName>
		<ButtonName>LossRatioButton</ButtonName>
	</GroupSchemeMaintenanceButtons>
    <ClientButtons/>
	<AllowedCommandsOther>
		<Command id="TEST_GENACCTRN"></Command>
		<Command id="DO_PRINT_LETTER"></Command>
		<Command id="CLEAR_SPOOL"></Command>
		<Command id="RUNNING_PROCESS"></Command>
		<Command id="DOWNLOAD_SPOOL"></Command>
		<Command id="SHOW_POLICY_IMAGES"></Command>
		<Command id="DO_PRINT_DOCUMENT"></Command>
		<Command id="PRINT_CONTRACT_NOTE"></Command>
	</AllowedCommandsOther>
</UserSecurity>

=== Financial-Information-Technology-Ltd/cdn/html/esurance/webmenu.xml
<?xml version="1.0"?>
<!DOCTYPE UserSecurity SYSTEM "..\menu.dtd">
<UserSecurity>
	<FitMenu>
		<Description>Web Menu</Description>
	</FitMenu>
	<AllowedCommands>
		<Command id="DO_POLICY_ENQUIRY"></Command>
		<Command id="EXPORT_POLICY_LIST"></Command>
		<Command id="POLICY_ENQUIRY"></Command>
		<Command id="DO_SHOW_POLICY"></Command>
		<Command id="POLICY_ACTIVITY"></Command>
		<Command id="SHOW_ONLINE_CC_PAYMENT"></Command>
		<Command id="PROCESS_ONLINE_CC_PAYMENT"></Command>
		<Command id="UNIT_MOVEMENTS"></Command>
		<Command id="UNIT_STATEMENT"></Command>
		<Command id="SHOW_ALL_POLICY_COMMISSIONS"></Command>
		<Command id="DO_SHOW_POLICY_FUND"></Command>
		<Command id="DO_HOME"></Command>
		<Command id="DO_SHOW_AGENT_STATEMENTS"></Command>
		<Command id="DO_SHOW_AGENT_STMT_DOCS"></Command>
		<Command id="LOGOUT"></Command>
		<Command id="SHOW_POLICY_FUND"></Command>
		<Command id="SHOW_DOC_IMAGE"></Command>
		<Command id="SHOW_BATCH_STATUS"></Command>
		<Command id="DO_ADMINISTRATION"></Command>
		<Command id="ADMINISTRATION"></Command>
		<Command id="CONFIGURATION"></Command>
		<Command id="SERGUEI_SPOOL"></Command>
		<Command id="SET_CURRENT_DATE"></Command>
		<Command id="EXISTING_QUOTES"></Command>
		<Command id="NEW_QUOTE"></Command>
		<Command id="NEW_BUSINESS"></Command>
		<Command id="DO_NEW_BUSINESS"></Command>
		<Command id="DO_GROUP_BUSINESS"></Command>
		<Command id="SHOW_GROUP"></Command>
		<Command id="SHOW_SUBGROUP"></Command>
		<Command id="SHOW_MEMBER_LIST"></Command>
		<Command id="GROUP_DATA"></Command>
		<Command id="SUBGROUP_DATA"></Command>
		<Command id="PROCESS_GROUP_BILL"></Command>
		<Command id="GROUP_BILL_SUMMARY"></Command>
		<Command id="GROUP_PREMIUMS"></Command>
		<Command id="UPLOAD_GROUP_BILL"></Command>
		<Command id="GROUP_SEARCH"></Command>
		<Command id="SELECT_AGENT"></Command>
		<Command id="PROCESS_SELECT_AGENT"></Command>
		<Command id="PROCESS_DISCLAIMER"></Command>
		<Command id="SHOW_POLICY_IMAGES"></Command>
		<Command id="SHOW_GROUP_IMAGES"></Command>
		<Command id="SHOW_DOC_IMAGE"></Command>
		<Command id="PROCESS_GROUP_QUOTE_SETUP"></Command>
		<Command id="SHOW_QUOTE_MEMBER_LIST"></Command>
		<Command id="GROUP_QUOTE_MEMBER_LIST"></Command>
		<Command id="GROUP_QUOTE_MEMBER"></Command>
		<Command id="SHOW_GROUP_QUOTE_MEMBER"></Command>
		<Command id="SHOW_GROUP_QUOTE"></Command>
		<Command id="SHOW_GROUP_QUOTE_SUBGROUP"></Command>
		<Command id="PROCESS_GROUP_QUOTE_SUBGROUP"></Command>
		<Command id="EXISTING_GROUP_QUOTES"></Command>
		<Command id="CLIENT_GROUP_QUOTE_LIST"></Command>
		<Command id="DOWNLOAD_SPOOL"></Command>
		<Command id="RUNNING_PROCESS"></Command>
		<Command id="IMPORT_QUOTE_MEMBERS"></Command>
		<Command id="LIST_CITIES"></Command>
		<Command id="MEMBER_LIST"></Command>
		<Command id="EDIT_MEMBER"></Command>
		<Command id="SHOW_MEMBER"></Command>
		<Command id="PROCESS_MEMBER"></Command>
		<Command id="GROUP_MEMBER_QUOTE"></Command>
		<Command id="GROUP_MEMBER_QUOTE_POST_ISSUE"></Command>
		<Command id="GROUP_MEMBER_LEAVE"></Command>
		<Command id="IMPORT_GROUP_MEMBERS"></Command>
		<Command id="EXPORT_GROUP_MEMBERS"></Command>
		<Command id="SHOW_FUND_SPLIT"></Command>
		<Command id="CHANGE_FUND_SPLIT"></Command>
		<Command id="SHOW_TBMVR_RATES"></Command>
		<Command id="CHANGE_TBMVR_RATES"></Command>
		<Command id="SHOW_POLICY_VALUE"></Command>
		<Command id="SWITCH_UNITS"></Command>
		<Command id="PROCESS_SWITCH_UNITS"></Command>
		<Command id="DO_SHOW_AGENT_PREMIUMS"></Command>
		<Command id="SHOW_AGENT_PREMIUMS"></Command>
		<Command id="DO_SHOW_AGENT_RECEIPTS"></Command>
		<Command id="SHOW_AGENT_RECEIPTS"></Command>
		<Command id="DO_SHOW_AGENT_LOANS"></Command>
		<Command id="DO_SHOW_AGENT_LOAN_TRANS"></Command>
		<Command id="DOWNLOAD_OUTSTANDING_PREMIUMS_BY_DATE"></Command>
		<Command id="DOWNLOAD_OUTSTANDING_PREMIUMS_BY_DATE_DO"></Command>
		<Command id="USER_HOME"></Command>
		<Command id="SELECT_FUND_LIST"></Command>
		<Command id="DO_CHANGE_PASSWORD"></Command>
		<Command id="CHANGE_PASSWORD"></Command>
		<Command id="SHOW_POLICY_VALUE_GRAPH"></Command>
		<Command id="SHOW_POLICY_VALUE_GRAPH_CHOOSE"></Command>
		<Command id="SHOW_POLICY_VALUE_GRAPH_IMG"></Command>
		<Command id="SHOW_FUND_SPLIT_PIE"></Command>
		<Command id="MEMBER_CHANGE_LIST"></Command>
		<Command id="BLOCKED_USERS_LIST"></Command>
		<Command id="DO_CLIENT_ENQUIRY"></Command>
		<Command id="DO_SHOW_CLIENT"></Command>
		<Command id="PREMIUM_STATEMENT"></Command>
		<Command id="DO_CONTACT_CS"></Command>
		<Command id="PROCESS_CONTACT_CS"></Command>
		<Command id="CREATE_BANK_ACCOUNT"></Command>
		<Command id="PROCESS_BANK_ACCOUNT"></Command>
		<Command id="DO_OTP"></Command>
		<Command id="RESEND_OTP"></Command>
	</AllowedCommands>
	<PolicyMaintenanceButtons />
	<GroupSchemeMaintenanceButtons />
    <ClientButtons/>
	<AllowedCommandsOther />
</UserSecurity>
